### ISSUE TITLE
Memory leak in Voxtral 4b

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [CrispStrobe/CrispASR#54]
Hi,

I've been testing Voxtral 4b on a long audio and noticed that the VRAM usage started low (about 4G VRAM) but then grew for each new 30s chunk. At the 49th chunk I hit an OOM error.

I'm suspecting a memory leak because I don't see any reason the VRAM should grew larger and larger like this over chunks.

I was interested in Voxtral 4b to check how much VRAM it's talking but so I'm left with no clear idea.

Edit: I'm confirming that every time I pass jfk.mp3 it gains about 420MB of VRAM.

**Comment by CrispStrobe** [comment]
thanks. will look into it. think i already see the bug...

**Comment by thiswillbeyourgithub** [comment]
Here's how I got the model:
```
hf download mistralai/Voxtral-Mini-4B-Realtime-2602
python models/convert-voxtral4b-to-gguf.py --input ~/.cache/huggingface/hub/models--mistralai--Voxtral-Mini-4B-Realtime-2602/snapshots/[id] --output voxtral-mini-4b-realtime.gguf
bin/crispasr-quantize ./voxtral-mini-4b-realtime.gguf ./voxtral-mini-4b-realtime_Q2_K.gguf  q2_k
```

**Comment by CrispStrobe** [comment]
Thanks for the report — confirmed and fixed in 393ca66.

**Root cause:** `voxtral4b_kv_init()` was unconditionally calling `ggml_init()` + `ggml_backend_alloc_buffer()` and overwriting `ctx->kv_ctx` / `ctx->kv_buf` on every call. The CLI backend (`crispasr_backend_voxtral4b.cpp`) calls `kv_init` once per audio slice, so each ~30 s chunk leaked the entire KV backend buffer (~256–512 MiB depending on dtype, layers, and `max_ctx`). The 3B sibling, `qwen3_asr`, `glm_asr`, `mimo_asr`, and `gemma4_e2b` all already had an `if (ctx->kv_k) return true;` guard for exactly this reason — voxtral4b and granite_speech were the two that were missing it.

**Fix:** add the same idempotent guard in both `voxtral4b_kv_init` and `granite_speech_kv_init`. After the first init, subsequent calls no-op.

**Verified locally:** `voxtral-mini-4b-realtime-q4_k.gguf` on Metal, `jfk.wav` × 50 ≈ 9 min audio, `-ck 10` (so ~55 chunks). With the fix, RSS holds at ~3115 MiB ± 5 MiB across the entire run (sampled every 8 s for 6+ minutes — no chunk-over-chunk growth). Without the fix, the same workload OOMs around chunk 49 per your report.

If you can re-test on your CUDA box and confirm VRAM is now flat across chunks, that would close out the issue.

**Comment by thiswillbeyourgithub** [comment]
Thanks.

I can't afford the time to build the container so let me know once a new image was created and I'll test it. Or I'll check at the next release.

**Comment by CrispStrobe** [comment]
Fixed in v0.5.7 (commit 0175f7c, just released).

Root cause was `voxtral4b_kv_init()` overwriting `ctx->kv_buf` and
`ctx->kv_ctx` on every call without freeing the previous backend
allocation, leaking the entire KV cache (~256-512 MiB depending on
dtype, layers, max_ctx) per chunk. The CLI's per-slice transcribe
path calls `kv_init` once per chunk, which is why the leak grew
linearly. Sibling backends (qwen3_asr, glm_asr, mimo_asr,
gemma4_e2b, voxtral 3B) all already had an `if (ctx->kv_k) return
true;` guard for exactly this reason; voxtral4b and granite_speech
were the two missing it. The fix adds the same guard to both.

Verified locally on M1 Metal with voxtral-mini-4b-realtime-q4_k.gguf
+ jfk.wav × 50 (~9 min, 55 chunks at -ck 10): RSS held at ~3115 MiB
± 5 MiB across the entire run, no chunk-over-chunk growth.

Release page: https://github.com/CrispStrobe/CrispASR/releases/tag/v0.5.7

If you can re-test on your CUDA box and confirm VRAM is now flat
across chunks, that would close this out for good. Thanks for the
report!

**Comment by thiswillbeyourgithub** [comment]
Confirmed fix! Thanks.

Loading the model seems to take about 1850MB of VRAM. After each chunk I see 2400MB being used.
